### ISSUE TITLE
In local mode there is an error "no object in the list"

### ISSUE THREAD

**Issue by Oxicid** [JulienHeijmans/quicksnap#30] opened 2022-10-22 22:51 UTC
It is not easy to cause this error, but I often run into it in a large project. As usual, press Ctrl+Shift+V and the error appears immediately, sometimes undoing a step (Ctrl+Z), this error disappears https://drive.google.com/file/d/1yVQUx4E8ed2LrdqocD173sTnwF7qmT_i/view?usp=sharing

**Comment by JulienHeijmans** [comment] 2022-10-23 10:52
Hi Oxicid,
THank you for taking the time to report the issue, and for giving a repro scene, this bug was reported in the past but I was not able to reproduce it, hopefully it will be easier with your scene!

**Comment by JulienHeijmans** [comment] 2022-10-23 10:59
Could you tell me how was the object Circle.012 hidden in the Layout workspace?
It might be something obvious, but I actually havn't been using Blender for a very long time.

**Comment by JulienHeijmans** [comment] 2022-10-23 13:38
Could you try to update to the latest version: 1.3.4 (You can do it from the addon preferences window)

The "no object in the list" should be fixed, and the tool should now behave properly in orthographic view, like your scene was using.
Tell me how it goes!

**Comment by Oxicid** [comment] 2022-10-23 13:47
I myself tried to reproduce this problem in a new file from scratch, I even somehow succeeded, but then somehow miraculously everything worked as usual. And I decided to simply duplicate the project file I was working on now - where this problem exists, removing everything unnecessary. At one point it seemed to me that the problem was on the program side. Checked the update, glad that the problem was solved! :)

**Comment by JulienHeijmans** [comment] 2022-10-23 14:24
It looks like the issue happened when you were in local view, so when you isolate objects using the "/" key. Cool to hear that it is fixed!

Thank you for reporting, I am also happy that I realized that the tool wasnt working in ortho view thanks to your scene :)

**Closed by JulienHeijmans** 2022-10-23 14:24 UTC
