### ISSUE TITLE
When you press ctrl+shift+v + Y an error pops up

### ISSUE THREAD

**Issue by Oxicid** [JulienHeijmans/quicksnap#36] opened 2022-11-02 02:37 UTC
Found a bug that is not particularly critical (it's not because of the latest fix). When you press ctrl+shift+v + Y (or any other axis that looks at the camera) pops up an error when trying to snapping (if the error does not pop up, then hold your mouse over the target vertex). https://drive.google.com/file/d/1WAqZPrMj7O-hr7JJnzFnzzNLUdlLfdv7/view?usp=sharing

**Comment by JulienHeijmans** [comment] 2022-11-02 11:48
Ah yes indeed, thank you for noticing and reporting !
You are helping make the tool more stable for everyone :D 

 The issue is fixed on main branch. I will make a new release when I have some more changes to push.
If you want to verify, you can manually get the latest version of the main branch in the addon preferences. Like so:

![674a07d6346286b19452a4ecc0e4f8e0](https://user-images.githubusercontent.com/35562774/199482225-09269923-1a68-4d5c-90b5-d915db307f10.gif)

**Closed** 2022-11-06 10:45 UTC
