### ISSUE TITLE
Error: RuntimeError: Trying to insert more items than KDTree has room for

### ISSUE THREAD

**Issue by Nocxr** [JulienHeijmans/quicksnap#14] opened 2022-10-17 05:34 UTC
After using quick snap successfully once, the first time trying to active it again results in the following error:

`Traceback (most recent call last):
  File "C:\Users\marsh\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\quicksnap-main\quicksnap.py", line 608, in invoke
    if not self.initialize(context):
  File "C:\Users\marsh\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\quicksnap-main\quicksnap.py", line 56, in initialize
    self.snapdata_source = SnapData(context, region, self.settings, self.selection_objects)
  File "C:\Users\marsh\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\quicksnap-main\quicksnap_snapdata.py", line 207, in __init__
    self.process_iteration(context)
  File "C:\Users\marsh\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\quicksnap-main\quicksnap_snapdata.py", line 422, in process_iteration
    self.balance_tree(start_insert_id, self.added_points_np)
  File "C:\Users\marsh\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\quicksnap-main\quicksnap_snapdata.py", line 398, in balance_tree
    insert(self.region_2d[i], i)
RuntimeError: Trying to insert more items than KDTree has room for
Error: Python: Traceback (most recent call last):
  File "C:\Users\marsh\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\quicksnap-main\quicksnap.py", line 608, in invoke
    if not self.initialize(context):
  File "C:\Users\marsh\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\quicksnap-main\quicksnap.py", line 56, in initialize
    self.snapdata_source = SnapData(context, region, self.settings, self.selection_objects)
  File "C:\Users\marsh\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\quicksnap-main\quicksnap_snapdata.py", line 207, in __init__
    self.process_iteration(context)
  File "C:\Users\marsh\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\quicksnap-main\quicksnap_snapdata.py", line 422, in process_iteration
    self.balance_tree(start_insert_id, self.added_points_np)
  File "C:\Users\marsh\AppData\Roaming\Blender Foundation\Blender\3.3\scripts\addons\quicksnap-main\quicksnap_snapdata.py", line 398, in balance_tree
    insert(self.region_2d[i], i)
RuntimeError: Trying to insert more items than KDTree has room for`

Trying to activate it again after this error shows does not result in the error and will function as normal, until the next successful snap operation.  Please see attached video showing me trying to activate the plugin after using it once: 

https://user-images.githubusercontent.com/72276215/196096448-bd4580d2-dd34-447b-a381-3159ed35a58f.mp4

The plugin is up to date according to its self in the addons menu, and this happened in Blender 3.3.0 as well as after I updated to 3.3.1 to see if that resolved it.  This isn't actually stopping me from using the plugin just a minor inconvenience.  Please let me know if there is anything else I can provide to help!

**Comment by JulienHeijmans** [comment] 2022-10-17 07:08
Hey! Yes, that's annoying. Could you tell me a bit more:
Does it always happen?
In the video you shared, is there only this cube in the scene and nothing else? (other objects) 
This bug happens when the add-on fails to estimate the amount of vertices/points in the scene. 
Could you also tell me what are the add-on options? The settings in the preferences. 

When I get back home I will try to do exactly the same as you did in the video, trying to reproduce the bug.

**Comment by Nocxr** [comment] 2022-10-17 07:54
Hey, thanks for the quick reply!  Yes it seems I can replicate this every second time I try it, I've restarted blender multiple times and tried with various different basic objects and it persists.  In the video it was just the cube in the scene yes, but I've rerecorded another video to show the scene tree as well: 

https://user-images.githubusercontent.com/72276215/196119291-3f4e034f-acbb-48a4-8b4f-717fb6984ddf.mp4

 QuickSnap settings: 
![image](https://user-images.githubusercontent.com/72276215/196119434-a418c47d-a173-4dde-a293-9976b45a9c2f.png)

All addons enabled: 
![image](https://user-images.githubusercontent.com/72276215/196119515-1a31dd2c-5edf-43b1-9a93-73b386176ce4.png)

Please let me know if there is anything else you'd like me to show or try if it can be of any help, and thanks again for the awesome plugin!

**Comment by JulienHeijmans** [comment] 2022-10-17 12:12
Ok, I can reproduce it here. Looks like I introduced a bug on the main branch some days ago.
But, that bug does not happen anymore on the other I am working on right now, that brings in snap from/to edge-midpoints and face center.

I think that instead of fixing this specific bug, I will just push the new branch on main and make it the new version of the addon.
I will do that today, it would be amazing if you could try it out and tell me if you encounter any issue with it.

By the way, in your video you snap verts together. At the moment those verts are not welded/merged togather, is that something that could be useful to add to the tool, you think?

**Comment by JulienHeijmans** [comment] 2022-10-17 15:28
You can try updating the addon (In the addon settings) to version 1.3.0, and see how things go there. Any feedback is also welcome.

**Comment by Nocxr** [comment] 2022-10-17 16:11
I updated to the newest version (1.3.0) using the addon settings function and tried again, and I am no longer receiving the error anymore.  I tried it multiple times with various objects, relaunched blender a few times as well and so far it has not shown up again.  

I just discovered the pie menu function and the extra options are awesome, I wish I had a tool like this a long time ago!  And having a quick option/key for toggling welding vertices would be useful/handy In my opinion, I was just using the auto merge vertices button near the top right so I am not sure if that works differently then what you had in mind?
![image](https://user-images.githubusercontent.com/72276215/196227772-f0f83b93-03da-481f-9041-36d262a26eb3.png)

So far I am very much enjoying the addon and I can't think of anything off the top of my head to suggest because it seems to do everything I've wanted from snapping so far already, if I do think of something I will be sure to let you know and I will keep using the addon frequently.  Thanks again!

**Comment by JulienHeijmans** [comment] 2022-10-17 16:55
>  I was just using the auto merge vertices button near the top right so I am not sure if that works differently then what you had in mind?

Ah yes, I actually did not know about this button there!
Looks like it is always displayed in Edit mode? I think I could just reuse that existing button then! :) I will add it to the feature list. Should be super easy/quick to do.
I am just a bit worried that some users do auto-merge like this without knowing it...

Thank you for coming here and talk about your issue! :)

**Comment by JulienHeijmans** [comment] 2022-10-18 11:56
Auto-Merge vertices has been added to the last version :)

I will also close this issue, as the problem you had was fixed. 
Thank you again for reporting!

**Closed by JulienHeijmans** 2022-10-18 11:56 UTC
